### ISSUE TITLE
open wikipedia page in new tab

### ISSUE THREAD

**Issue by gminova** [fac-17/week4_MEIA_Autocomplete#14]
Is it possible to open the page in new tab instead of redirecting the user?

**Comment by tonylomax** [comment]
Also when you navigate to a wikipedia page and go back the input value is saved (though this may be a browser feature) is it possible to reset this?

**Comment by rooberrydev** [comment]
we thought that opening in a new tab would be unnecessary as a user would search for one thing at a time. hitting back is easier than navigating through tabs.

storing the input value is default browser behavior, nothing to do with our code. not sure how to override this
