### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by tonylomax** [fac-17/week4_MEIA_Autocomplete#15]
Amazing work, looks great!

![](https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif)

**Comment by gminova** [comment]
I really love the design! Very clean and simple. :))

![](https://media.giphy.com/media/3o7btSt2Et1GgIaDAY/giphy.gif)

**Comment by Oliversw** [comment]
![](https://media.giphy.com/media/8PdA6oDWZz0EjAyuXg/giphy.gif)

**Comment by crianonim** [comment]
Thank you!
