### ISSUE TITLE
Your UL looks so great! :) 

### ISSUE THREAD

**Issue by xIrusux** [fac-17/week4_MEIA_Autocomplete#19]
Guys! loving your liiissstt. We used a datalist tag which is a native method for autofiltering the suggestions in the list. Check it out if you have never heard about it!. Downfall is that your browser styles the dropdown for you and you have hardly any options to style it. Hence why I like the style of your list so much - well done!
 
https://www.w3schools.com/tags/tag_datalist.asp
"The <datalist> tag is used to provide an "autocomplete" feature on <input> elements. Users will see a drop-down list of pre-defined options as they input data."

**Comment by crianonim** [comment]
Thank you!
