### ISSUE TITLE
Awesome that you have so many comments in your code - makes it easy to follow 

### ISSUE THREAD

**Issue by xIrusux** [fac-17/week4_MEIA_Autocomplete#21]

**Comment by Oliversw** [comment]
This is so important!! 😍

**Comment by Oliversw** [comment]
I would add that I love the way that you broke everything down in the `/search` part of your router!! The comments in `router(first-draft).js` are really amazing too! I think it would be nice if they made their way into your actual `router.js` file as well since they are super helpful!

**Comment by sarahyjja** [comment]
Thanks Oliver! 
That's true, commenting can be very helpful! 
But I do also think that too much comments isn't great. The code should be readable without comment (or at least a very tiny amount to inform). I think, it's very important to find a balance into it ;)
