### ISSUE TITLE
Commit Numbers

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week4_MEIA_Autocomplete#24]
If you have a look at your [insights page](https://github.com/fac-17/week4_MEIA_Autocomplete/pulse) there is a bit of an imbalance between the number of commits that people on the team have made. That's not at all to say that they all need to be the same though! We all have different commit practices, and sometimes when we're pairing, it is easy to do all of the commits on a single computer.

I'd suggest not focusing on this too much, but it's worth being aware of!

**Comment by andy-mc-donald** [comment]
Noted! I was ill this week and wasn't in on Wednesday, so missed a chuck of the build process (so my commit count is well down this week :(
