### ISSUE TITLE
Installation instructions in readme

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week4_MEIA_Autocomplete#25]
I have to start off with pointing out that the readme is wonderful!! I love all of the planning and whiteboarding in it, as well as the gif!! I cracked up when I saw it.

The only thing that I would suggest including is a small 'Installation instructions' section. Even if it is as simple as cloning the repo and running `npm i`, it is worth being explicit about in the readme. Particularly for code review! Things will be getting more complicated with installation soon, so it's good to be aware of  :)

**Comment by sarahyjja** [comment]
👍
