### ISSUE TITLE
Gitignore tip

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week4_MEIA_Autocomplete#28]
Just a quick tip! If you select to initialize a Github repo with a .gitignore file and select node, it will prepopulate one for you that contains most of the files and folders that you might run into and want to ignore. Totally unnecessary for right now but good to be aware of!

**Comment by rooberrydev** [comment]
THANKYOU THIS WAS VERY USEFUL INFORMATION @Oliversw

**Comment by crianonim** [comment]
Thank you so much, I never noticed this dropdown there!
