### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week4_MEIA_Autocomplete#31]
There are tests!

And they pass!! 

Testing is often tough to fit in with everything else in such a short time frame, so well done! Looks fantastic 😄 

![](https://media.giphy.com/media/5VKbvrjxpVJCM/giphy.gif)

**Comment by tonylomax** [comment]
![keanu](https://media.giphy.com/media/kf3QCijQ76X5lqcutq/giphy.gif)
